[build-system]
requires = ["scikit-build-core", "nanobind", "jax>=0.4.31"]
build-backend = "scikit_build_core.build"

[project]
name = "jax_jit_static_array"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["jax"]

[project.optional-dependencies]
test = ["pytest"]
